@startuml
!define ACTIVATE_ENTITY Repository <<Database>> #008000
skinparam Style strictuml

actor User
participant DeleteClassPostView
participant ClassPostController
participant ClassPostService
'participant Exception
'participant Dto
database Repository as ACTIVATE_ENTITY

User -> ClassPostController: Send request
activate ClassPostController
ClassPostController -> ClassPostService: deleteClassPost()
activate ClassPostService
ClassPostService -> Repository : Process and delete class Post
activate Repository
Repository --> ClassPostService : Return Mess " Delete successfully"
deactivate
ClassPostService --> ClassPostController : Send Mess
deactivate
ClassPostController --> DeleteClassPostView : Send Mess
deactivate
activate DeleteClassPostView
DeleteClassPostView --> User : Display Mess
deactivate



@enduml
