@startuml

class DashboardUserController {
    - userService: UserService
    + addUser(userDTO: UserDTO): ResponseEntity<String>
}

class UserService {
    - validate: ValidationService
    - passwordEncoder: PasswordEncoder
    - userRepository: UserRepository
    - roleRepository: RoleRepository
    + addUser(userDTO: UserDTO): void
}

class UserDTO {

}

class ValidationService {
    + checkUserDTO(userDTO: UserDTO): void
}

class UserMapper {
    + toUserDTO(userDTO: UserDTO): User
}

class RoleRepository {
    + findRoleByRoleId(roleId: Long): Role
}


class UserRepository {
    + save(user: User): User
}



DashboardUserController --> UserService : <<use>>
UserService --> ValidationService : <<use>>
UserService --> UserRepository : <<use>>
UserService --> RoleRepository : <<use>>
UserService --> UserMapper : <<use>>
DashboardUserController --> UserDTO : <<use>>

@enduml
